# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Vonage-Click2Call
version:      0.11
version_from: lib/Vonage/Click2Call.pm
installdirs:  site
requires:
    LWP::UserAgent:                1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
